-- Ona Analytics: Database Migration
-- Amazon Aurora PostgreSQL + pgvector

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Organizations
CREATE TABLE IF NOT EXISTS org_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  timezone VARCHAR(64) DEFAULT 'Africa/Nairobi',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Relational demand data (occupancy metrics)
CREATE TABLE IF NOT EXISTS demand_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES org_profiles(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  metric_type VARCHAR(50) NOT NULL DEFAULT 'occupancy_rate',
  actual_value DECIMAL(12, 4) NOT NULL,
  predicted_value DECIMAL(12, 4),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_demand_logs_org_date
  ON demand_logs(org_id, log_date DESC);

CREATE INDEX IF NOT EXISTS idx_demand_logs_org_metric
  ON demand_logs(org_id, metric_type);

-- 4. Vector embeddings (RAG context for SOPs)
CREATE TABLE IF NOT EXISTS context_knowledge (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES org_profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  embedding VECTOR(10) NOT NULL,
  -- Note: In production, use VECTOR(1536) for text-embedding-3-small
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_context_knowledge_org
  ON context_knowledge(org_id);

CREATE INDEX IF NOT EXISTS idx_context_knowledge_embedding
  ON context_knowledge USING hnsw (embedding vector_cosine_ops);

-- 5. Procurement recommendations (generated by the Ona Agent)
CREATE TABLE IF NOT EXISTS procurement_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES org_profiles(id) ON DELETE CASCADE,
  item_name VARCHAR(255) NOT NULL,
  required_amount DECIMAL(12, 2) NOT NULL,
  unit VARCHAR(50) NOT NULL DEFAULT 'units',
  urgency VARCHAR(20) NOT NULL DEFAULT 'medium'
    CHECK (urgency IN ('high', 'medium', 'low')),
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  fulfilled_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_procurement_org_urgency
  ON procurement_items(org_id, urgency);

-- 6. Agent conversation logs (for audit / debugging)
CREATE TABLE IF NOT EXISTS agent_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES org_profiles(id) ON DELETE CASCADE,
  user_message TEXT NOT NULL,
  agent_response TEXT NOT NULL,
  tool_calls JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_conversations_org
  ON agent_conversations(org_id, created_at DESC);
