-- Ona Analytics: Seed Data
-- Run after schema migration

-- 1. Create a demo camp
INSERT INTO org_profiles (id, name, location, timezone)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Olare Orok Eco-Lodge',
  'Maasai Mara, Kenya',
  'Africa/Nairobi'
);

-- 2. Historical occupancy data (14 days of real data)
DELETE FROM demand_logs WHERE org_id = '11111111-1111-1111-1111-111111111111';
INSERT INTO demand_logs (org_id, log_date, metric_type, actual_value, predicted_value)
VALUES
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '13 days', 'occupancy_rate', 42.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '12 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '11 days', 'occupancy_rate', 39.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '10 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '9 days', 'occupancy_rate', 43.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '8 days', 'occupancy_rate', 38.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '7 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '6 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '5 days', 'occupancy_rate', 42.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '4 days', 'occupancy_rate', 39.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '3 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '2 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '1 day', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE, 'occupancy_rate', 41.0, NULL),

  -- Predicted spike over the weekend
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '1 day', 'occupancy_rate', NULL, 48.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '2 days', 'occupancy_rate', NULL, 75.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '3 days', 'occupancy_rate', NULL, 95.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '4 days', 'occupancy_rate', NULL, 93.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '5 days', 'occupancy_rate', NULL, 65.0);

-- 4. SOP context knowledge for RAG (with pgvector embeddings)
-- Note: In production, embeddings are generated by the AI model.
-- These are placeholder vectors that should be replaced with real embeddings via the AI SDK embedding model.

INSERT INTO context_knowledge (id, org_id, content, embedding)
VALUES
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'Weather SOP: If heavy rain is forecasted, supply trucks must depart 12 hours earlier due to severe mud on the Sekenani gate road.',
   ARRAY[0.1, 0.05, -0.02, 0.15, -0.08, 0.12, -0.03, 0.07, 0.01, -0.06]::vector),

  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'Fresh Supply SOP: Each occupied tent requires 4kg of fresh produce daily. For 25 tents at full occupancy, procure 100kg of mixed vegetables and fruits every 3 days.',
   ARRAY[0.08, 0.12, -0.05, 0.02, 0.1, -0.01, 0.15, -0.07, 0.03, 0.09]::vector),

  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'Gas and Fuel SOP: Each gas cylinder serves 5 tented suites for 7 days. During high occupancy (>80%), increase propane delivery by 50% and schedule bi-weekly refills.',
   ARRAY[0.15, -0.03, 0.08, -0.1, 0.05, 0.12, -0.06, 0.02, 0.11, -0.04]::vector),

  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111',
   'Linens SOP: Laundry turnaround requires 24 hours. At >90% occupancy, maintain 3 full sets of linens per tent (one on bed, one in laundry, one in storage).',
   ARRAY[0.05, 0.15, -0.08, 0.03, -0.02, 0.1, 0.07, -0.12, 0.04, 0.01]::vector);

-- 5. Procurement items generated by the agent
DELETE FROM procurement_items WHERE org_id = '11111111-1111-1111-1111-111111111111';
INSERT INTO procurement_items (id, org_id, item_name, required_amount, unit, urgency, reason)
VALUES
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111', 'Fresh Produce', 40, 'kg', 'high',
   'Weekend surge to 95% occupancy requires +40kg additional fresh produce per SOP'),
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111', 'Gas Cylinders', 10, 'units', 'high',
   'Occupancy spike above 80% triggers 50% increase in propane supply per Gas SOP'),
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111', 'Linens & Bedding', 25, 'sets', 'medium',
   'Additional 25 linen sets needed for 3-set rotation at peak occupancy');
