-- Ona Analytics: Seed Data
-- Safe for development only; do not apply to production
-- All inserts are idempotent (ON CONFLICT ... DO NOTHING)

-- 1. Demo camp
INSERT INTO org_profiles (id, name, location, timezone)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Olare Orok Eco-Lodge',
  'Maasai Mara, Kenya',
  'Africa/Nairobi'
)
ON CONFLICT (id) DO NOTHING;

-- 2. Historical occupancy data (14 days)
INSERT INTO demand_logs (org_id, log_date, metric_type, actual_value, predicted_value)
VALUES
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '13 days', 'occupancy_rate', 42.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '12 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '11 days', 'occupancy_rate', 39.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '10 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '9 days', 'occupancy_rate', 43.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '8 days', 'occupancy_rate', 38.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '7 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '6 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '5 days', 'occupancy_rate', 42.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '4 days', 'occupancy_rate', 39.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '3 days', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '2 days', 'occupancy_rate', 40.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE - INTERVAL '1 day', 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE, 'occupancy_rate', 41.0, NULL),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '1 day', 'occupancy_rate', NULL, 48.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '2 days', 'occupancy_rate', NULL, 75.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '3 days', 'occupancy_rate', NULL, 95.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '4 days', 'occupancy_rate', NULL, 93.0),
  ('11111111-1111-1111-1111-111111111111', CURRENT_DATE + INTERVAL '5 days', 'occupancy_rate', NULL, 65.0)
ON CONFLICT (org_id, log_date, metric_type) DO NOTHING;

-- 3. Seed admin user
INSERT INTO camp_users (id, org_id, email, password_hash, name, role, must_change_password)
VALUES (
  gen_random_uuid(),
  '11111111-1111-1111-1111-111111111111',
  'admin@ona-analytics.com',
  '$2b$12$LJ3m4ys3Lg3YOCwLTI3tYe3VqZ5wYKGzKmR0GqBnKLMnXKJx8jQy.',
  'Admin User',
  'admin',
  TRUE
)
ON CONFLICT (email) DO NOTHING;

-- 4. SOP context knowledge embeddings
-- Run lib/db/seed-embeddings.sql separately to insert pgvector embeddings
-- (1536-dim vectors are verbose and stored in a companion file)
-- The embeddings file is auto-generated by: node scripts/generate-seed.mjs

-- 5. Procurement items
INSERT INTO procurement_items (id, org_id, item_name, required_amount, unit, urgency, reason)
SELECT * FROM (VALUES
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111'::uuid, 'Fresh Produce', 40, 'kg', 'high',
   'Weekend surge to 95% occupancy requires +40kg additional fresh produce per SOP'),
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111'::uuid, 'Gas Cylinders', 10, 'units', 'high',
   'Occupancy spike above 80% triggers 50% increase in propane supply per Gas SOP'),
  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111'::uuid, 'Linens & Bedding', 25, 'sets', 'medium',
   'Additional 25 linen sets needed for 3-set rotation at peak occupancy')
) AS v
WHERE NOT EXISTS (
  SELECT 1 FROM procurement_items WHERE org_id = '11111111-1111-1111-1111-111111111111'::uuid
);
