import fs from "fs"

const vectors = [
  [0.1012, 0.0513, -0.0214, 0.1515, -0.0816, 0.1217, -0.0318, 0.0719, 0.012, -0.0621],
  [0.0822, 0.1223, -0.0524, 0.0225, 0.1026, -0.0127, 0.1528, -0.0729, 0.033, 0.0931],
  [0.1532, -0.0333, 0.0834, -0.1035, 0.0536, 0.1237, -0.0638, 0.0239, 0.114, -0.0441],
  [0.0542, 0.1543, -0.0844, 0.0345, -0.0246, 0.1047, 0.0748, -0.1249, 0.045, 0.0151],
]

const contents = [
  "Weather SOP: If heavy rain is forecasted, supply trucks must depart 12 hours earlier due to severe mud on the Sekenani gate road.",
  "Fresh Supply SOP: Each occupied tent requires 4kg of fresh produce daily. For 25 tents at full occupancy, procure 100kg of mixed vegetables and fruits every 3 days.",
  "Gas and Fuel SOP: Each gas cylinder serves 5 tented suites for 7 days. During high occupancy (>80%), increase propane delivery by 50% and schedule bi-weekly refills.",
  "Linens SOP: Laundry turnaround requires 24 hours. At >90% occupancy, maintain 3 full sets of linens per tent (one on bed, one in laundry, one in storage).",
]

function makeVectorSQL(values) {
  const arr = new Array(1536).fill("0")
  for (let i = 0; i < values.length; i++) arr[i] = String(values[i])
  const lines = []
  for (let i = 0; i < arr.length; i += 12) {
    lines.push("    " + arr.slice(i, i + 12).join(","))
  }
  return "  ARRAY[\n" + lines.join(",\n") + "\n  ]::vector"
}

let sql = ""
for (let i = 0; i < 4; i++) {
  const vec = makeVectorSQL(vectors[i])
  sql +=
    "  (gen_random_uuid(), '11111111-1111-1111-1111-111111111111'::uuid,\n" +
    "   '" + contents[i].replace(/'/g, "''") + "',\n" +
    vec +
    ")"
  if (i < 3) sql += ",\n\n"
  else sql += ";\n"
}

const fullSql = `-- Ona Analytics: Context Knowledge Embeddings
-- Generated by scripts/generate-seed.mjs
-- 1536-dimension vectors for pgvector (text-embedding-3-small)

INSERT INTO context_knowledge (id, org_id, content, embedding)
VALUES

${sql}
`

fs.writeFileSync("lib/db/seed-embeddings.sql", fullSql)
console.log("Generated lib/db/seed-embeddings.sql (" + fullSql.split("\n").length + " lines)")
